repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: mixed-line-ending
    - id: trailing-whitespace
 - repo: https://github.com/pycqa/flake8
   rev: 6.0.0
   hooks:
    - id: flake8
      args: ["--config=.flake8"]
      types: [python]
 - repo: https://github.com/ambv/black
   rev: 23.3.0
   hooks:
    - id: black
      language_version: python3.9
 - repo: https://github.com/pycqa/isort
   rev: 5.12.0
   hooks:
    - id: isort
      name: isort (python)
      files: (^thonnycontrib/)
      types: [python]
 - repo: https://github.com/PyCQA/bandit
   rev: 1.7.5
   hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      files: (^thonnycontrib/)
      types: [python]
      additional_dependencies: [ "bandit[toml]" ]

 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.3.0
   hooks:
    - id: mypy
      files: ^thonnycontrib/
      types: [python]

