name: Build and test worker

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: The OS to run on.
      pytest-debug:
        required: false
        type: string
        description: Set this to make pytest emit debug logs.
      python-version:
        required: true
        type: number
        description: The python version to run.

permissions:
  contents: read
  pull-requests: read

jobs:
  build_and_test_python:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip'
      - name: Build and test python
        run: |
          if [ -n "${{ inputs.pytest-debug }}" ]; then
            export PYTEST_DEBUG=1
          fi
          make build_python
      - name: Notify alerts channel of failure
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Failure Message
          MSG_MINIMAL: actions url, commit, ref
          SLACK_FOOTER: Build failure

