name: Deploy scheduler

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy_matrix:
    # TODO define this only once for all workflows!
    strategy:
      # fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    uses: ./.github/workflows/deploy_worker.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit

